[build]
  # Set the base directory to the frontend directory
  base = "Frontend"
  # Specify the directory that will be deployed as public-facing content
  publish = "Frontend"
  # Point to the directory where serverless functions are stored
  functions = "Backend/netlify/functions"
  # Optional command to install dependencies before build
  command = "npm install"

[[redirects]]
  # Redirect frontend routes properly (for frontend routing in Single Page Applications)
  from = "/*"
  to = "/index.html"
  status = 200
